Exception on /translate [POST]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\app\routes.py", line 246, in translate_text
    request.formk['dest_language'])})
AttributeError: 'Request' object has no attribute 'formk'
Exception on /translate [POST]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\app\routes.py", line 246, in translate_text
    request.form['dest_language'])})
AttributeError: 'Request' object has no attribute 'formk'
Microblog startup
Exception on /translate [POST]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\app\routes.py", line 244, in translate_text
    return jsonify({'text': translate(request.form['text'],
  File "C:\Users\gabri\Desktop\Microblog\Microblog_Flask\app\translate.py", line 8, in translate
    return _('Error: the translation service is not configured.')
NameError: name '_' is not defined
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
Microblog startup
